include(${CMAKE_CURRENT_LIST_DIR}/dev)

set(OMTALK_COMPILER ON CACHE BOOL "")
set(OMTALK_CORE ON CACHE BOOL "")
set(OMTALK_GC ON CACHE BOOL "")
set(OMTALK_LLVM ON CACHE BOOL "")
set(OMTALK_OM ON CACHE BOOL "")