# Pre-populated cmake cache for regular development

set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "")
set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "")
set(OMTALK_ASAN ON CACHE BOOL "")
set(OMTALK_COMPILER ON CACHE BOOL "")
set(OMTALK_CORE ON CACHE BOOL "")
set(OMTALK_GC ON CACHE BOOL "")
set(OMTALK_LLD OFF CACHE BOOL "")
set(OMTALK_LLVM ON CACHE BOOL "")
set(OMTALK_OM ON CACHE BOOL "")
set(OMTALK_TESTS ON CACHE BOOL "")
set(OMTALK_UBSAN ON CACHE BOOL "")
set(OMTALK_WARNINGS ON CACHE BOOL "")