# Pre-populated cmake cache for regular development. Does not enable any project
# components.

set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "")
set(CMAKE_CXX_FLAGS -fdiagnostics-color CACHE STRING "")
set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "")
set(OMTALK_CCACHE ON CACHE BOOL "")
set(OMTALK_SAN_ASAN ON CACHE BOOL "")
set(OMTALK_SAN_UBSAN ON CACHE BOOL "")
set(OMTALK_STATIC_CLANG_TIDY ON CACHE BOOL "")
set(OMTALK_STATIC_IWYU ON CACHE BOOL "")
set(OMTALK_TESTS ON CACHE BOOL "")
set(OMTALK_WARNINGS ON CACHE BOOL "")
set(OMTALK_WARNINGS_AS_ERRORS ON CACHE BOOL "")