# Pre-populated cmake cache for regular development
set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "")
set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "")
set(OMTALK_ASAN ON CACHE BOOL "")
set(OMTALK_LLD OFF CACHE BOOL "")
set(OMTALK_SPLIT_DEBUG OFF CACHE BOOL "Does not work yet")
set(OMTALK_UBSAN ON CACHE BOOL "")
set(OMTALK_WARNINGS ON CACHE BOOL "")
