# Cache file for the Garbage Collector only

set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "")
set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "")
set(OMTALK_GC ON CACHE BOOL "")
set(OMTALK_TESTS ON CACHE BOOL "")
set(OMTALK_UBSAN ON CACHE BOOL "")
set(OMTALK_WARNINGS ON CACHE BOOL "")
