#include <ab/Util/BitArray.h>
#include <catch2/catch.hpp>
#include <example/Object.h>
#include <iostream>
#include <om/GC/Allocate.h>
#include <om/GC/Handle.h>
#include <om/GC/Heap.h>
#include <om/GC/MemoryManager.h>
#include <om/GC/Ref.h>
