set(AB_PROJECT ON CACHE BOOL "")
# Compiler support is disabled by default
set(OM_COMPONENT_COMPILER OFF CACHE BOOL "")
set(OM_COMPONENT_GC ON CACHE BOOL "")
set(OM_COMPONENT_OM ON CACHE BOOL "")
set(OM_PROJECT ON CACHE BOOL "")